[package]
edition = "2021"
name = "poke6-seed-finder"
version = "0.1.0"

[dependencies]
dialoguer = "0.11.0"
indicatif = {version = "0.17.7", features = ["rayon"]}
multiversion = "0.7.3"
rayon = "1.8.0"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
