[package]
name = "gen6_mt_seed_finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mersenne_twister = "*"
rand = "*"
rayon = "*"
indicatif = { version = "*", features = ["rayon"] }
